# Generated by Django 4.0.6 on 2022-09-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_no', models.CharField(max_length=20)),
                ('fullname', models.CharField(max_length=20)),
                ('fathername', models.CharField(max_length=50)),
                ('starts_on', models.CharField(max_length=100)),
                ('ends_on', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
            ],
        ),
    ]
